name: Renovate
on:
  workflow_call:
    inputs:
      dryRun:
        type: boolean
        required: false
        # True until we launch
        default: true
        description: Dry run (don't create PRs)
      debugMode:
        type: boolean
        required: false
        default: false
        description: Run Renovate with debug logging
    secrets:
      DEPENDENCY_UPDATES_PRIVATE_KEY:
        required: true
      FEEDZIO_PUBLISH_API_KEY:
        required: false
jobs:
  renovate:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}/${{ github.ref_name }}
    steps:
      - name: Get token
        id: get-token
        uses: actions/create-github-app-token@v2.1.4
        with:
          app-id: 1486299
          private-key: ${{ secrets.DEPENDENCY_UPDATES_PRIVATE_KEY }}
          owner: Particular
      - name: Checkout config
        uses: actions/checkout@v5.0.0
        with:
          repository: Particular/renovate-config
          token: ${{ steps.get-token.outputs.token}}
          ref: main
          path: renovate-config
      - name: Create repository config if necessary
        shell: pwsh
        run: |
          $path = 'renovate-config/${{ github.event.repository.name }}/config.json'
          $exists = Test-Path $path -PathType Leaf
          if ($exists -eq $False) {
            New-Item -ItemType File -Path $path -Force
            Copy-Item renovate-config/default-repo-config.json -Destination $path -Force
          }
      - name: Run Renovate
        uses: renovatebot/github-action@v43.0.18
        with:
          configurationFile: "renovate-config/${{ github.event.repository.name }}/config.json"
          token: ${{ steps.get-token.outputs.token }}
        env:
          RENOVATE_PLATFORM: github
          RENOVATE_REPOSITORIES: ${{ github.repository }}
          RENOVATE_ONBOARDING: false
          RENOVATE_REQUIRE_CONFIG: optional
          LOG_LEVEL: ${{ inputs.debugMode && 'debug' || 'info'}}
          RENOVATE_DRY_RUN: ${{ inputs.dryRun && 'full' || null }}
          RENOVATE_HOST_RULES: >
            [
              {
                "hostType": "nuget",
                "matchHost": "f.feedz.io",
                "username": "Private Feed Access",
                "password": "${{ secrets.FEEDZIO_PUBLISH_API_KEY }}"
              }
            ]
