name: Renovate
on:
  workflow_call:
    inputs:
      dryRun:
        type: boolean
        required: false
        # True until we launch
        default: true
        description: Dry run (don't create PRs)
      debugMode:
        type: boolean
        required: false
        default: false
        description: Run Renovate with debug logging
    secrets:
      DEPENDENCY_UPDATES_PRIVATE_KEY:
        required: true
      FEEDZIO_PUBLISH_API_KEY:
        required: false
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Get token
        id: get-token
        uses: actions/create-github-app-token@v2.0.6
        with:
          app-id: 1486299
          private-key: ${{ secrets.DEPENDENCY_UPDATES_PRIVATE_KEY }}
      - name: Checkout repo
        uses: actions/checkout@v4.2.2
        with:
          path: main
      - name: Checkout common config
        uses: actions/checkout@v4.2.2
        with:
          repository: Particular/shared-workflows
          path: config
          sparse-checkout: renovate
          # Don't need to fetch the shared-workflows repo's root files
          sparse-checkout-cone-mode: false
      - name: Output global config
        run: cat config/renovate/global-config.json5
      - name: Run Renovate
        uses: renovatebot/github-action@v43.0.0
        with:
          configurationFile: config/renovate/global-config.json5
          token: ${{ steps.get-token.outputs.token }}
        env:
          RENOVATE_REPOSITORIES: ${{ github.repository }}
          LOG_LEVEL: ${{ inputs.debugMode && 'debug' || 'info'}}
          RENOVATE_DRY_RUN: ${{ inputs.dryRun && 'full' || null }}
          RENOVATE_HOST_RULES: >
            [
              {
                "hostType": "nuget",
                "matchHost": "f.feedz.io",
                "username": "Private Feed Access",
                "password": "${{ secrets.FEEDZIO_PUBLISH_API_KEY }}"
              }
            ]
