name: NuGet audit

on:
  workflow_call:
    secrets:
      FUNCTIONS_AUTHKEY:
        required: true
      PROCESSNUGETAUDITRESULTS_URL:
        required: true

jobs:
  nuget-audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.3
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v5.3.0
        with:
          global-json-file: global.json
      - name: .NET Restore
        id: restore
        shell: bash
        run: |
          mkdir -p ${{ github.workspace }}/results

          dotnet restore src > "${{ github.workspace }}/results/dotnetrestore.log" 2>&1 || true
          cat "${{ github.workspace }}/results/dotnetrestore.log"

          CVECOUNT=$(awk '/NU190[1-4]/ { count++ } END { print count + 0 }' "${{ github.workspace }}/results/dotnetrestore.log")

          echo "cvecount=${CVECOUNT}" >> "$GITHUB_OUTPUT"

          echo "Found $CVECOUNT CVEs"
      - name: Upload results when CVEs detected
        if: ${{ steps.restore.outputs.cvecount > 0 }}
        shell: bash
        working-directory: ./src
        run: |
          (dotnet list package --vulnerable --include-transitive --format json | jq '{"vulnerabilities": .}'; jq -s '{ "projectAssets": .}' */obj/project.assets.json) | jq -s add >> ${{ github.workspace }}/results/restoreData.json
          curl -X POST \
             -F "repository_id=${{ github.repository_id }}" \
             -F "branch=${{ github.ref_name }}" \
             -F "commit=${{ github.sha }}" \
             -F "restoreDataFile=@${{ github.workspace }}/results/restoreData.json" \
             -H "x-functions-key: ${{ secrets.FUNCTIONS_AUTHKEY }}" \
             ${{ secrets.PROCESSNUGETAUDITRESULTS_URL }}
      - name: Archive files when CVEs detected
        if: ${{ steps.restore.outputs.cvecount > 0 }}
        uses: actions/upload-artifact@v7
        with:
          name: files
          path: ${{ github.workspace }}/results/
